### ISSUE TITLE
Suggestion/Request !"This can help to run shaders on most of the devices"!

### ISSUE THREAD

**Issue by DiweshThakur** [Cubeir/Vanilla-RTX#24]
The Texture works fine but when disabling Upscaling It crashes!
I want to disable this option as to lower the input lag and resolution to Default Minecraft Textures 

Redmi Note 4
3GB RAM
Andreno GPU 506
Processor Snapdragon 625 2.02 GHz

(Request/Suggestion)
Please make a simplified version of this Shaders with all this same only change those *"3d Textures to Default Minecraft Textures" and "Turning Upscaling OFF by default"* so that most of the users will be able to use it without much issues.

Please implement this Feature 😇😊

**Comment by CubeIR** [comment]
It is likely that this happens because of the low amount of RAM on your device.
Considering that Vanilla PBR is a tremendous pack in its current state, disabling Upscaling makes the RAM usage go high enough to cause a crash.

So as you pointed out, perhaps a "Lite" version sort-of thing could help devices with low RAM.

**Comment by DiweshThakur** [comment]
> It is likely that this happens because of the low amount of RAM on your device. Considering that Vanilla PBR is a tremendously large pack in its current state, disabling Upscaling makes the RAM usage go high enough to cause a crash.
> 
> So as you pointed out, perhaps a "Lite" version sort-of thing could help devices with low RAM.

(Request)
•So Can you make a Shaders pack with just Dynamics Shadows, 
                                    as most of Minecraft's player community wants dynamic shadows.

(2 Bugs)
•Sometimes when loading in with Shaders the world gets dark or black re-selecting fixes this.

•When Turning off Beautiful Sky the shadows just disappear and sky gets black *"I don't know if it's a bug or not confirm"*

(Question)
•And can you explain me what Upscaling actually means as I searched about it and found out that it increases the resolution and input a lot of lag?

**Comment by Cubeir** [comment]
A cut-down version of Vanilla PRB with less demanding configurations is now available alongside regular Vanilla PBR.
However this version is not maintained on GitHub and remains limited to its MCPEDL page.
This is because for this lite variant, after an update is complete I simply edit it by hand to make it less demanding, these edits are not always the same and vary from update to update depending on what's new, necessary to be removed, etc...
