### ISSUE TITLE
Issues with a few textures

### ISSUE THREAD

**Issue by MistakingManx** [CubeIR/Vanilla-RTX#25]
~~Blocks like lanterns give off too little lighting when in nature.~~
- I don't know what exactly changed, but this is no longer an issue, it seems to provide lighting correctly now.

In some of the art shown and videos of this pack, I see mobs with glowing eyes, but none of the mobs have any glowing aspects at all.
![image](https://github.com/CubeIR/Vanilla-RTX/assets/28667267/5b5c0b5e-2d71-4351-a556-56af973c34ee)
![image](https://github.com/CubeIR/Vanilla-RTX/assets/28667267/cba62f59-3292-4f04-991b-3c4bd07e0433)
- Also, the warden looks like this for some reason;
![image](https://github.com/CubeIR/Vanilla-RTX/assets/28667267/c8b5e9ab-a946-4177-a7d5-2e04ff81fcae)
![image](https://github.com/CubeIR/Vanilla-RTX/assets/28667267/a8d50907-06ff-4eaa-b3c6-ecfd5e8964b8)
![image](https://github.com/CubeIR/Vanilla-RTX/assets/28667267/c7108728-ebee-4441-9019-dfa7647cd9a2)

Also if you have any other global resources that have a panorama background, no matter the ordering, the panorama shows up as pitch black, or a glitched out version of the last frame of the last world you were in;
_(if you can't fix it, could you tell me why it happens? Curiosity)_
![image](https://github.com/CubeIR/Vanilla-RTX/assets/28667267/3303fc8f-dbf6-4e06-ae9b-9048c20236be)
![image](https://github.com/CubeIR/Vanilla-RTX/assets/28667267/681802d9-62b6-41bc-a0ad-e8e44a2f6d48)
- the green part flashes a lot

Spec: Windows 10, Nvidia GeForce RTX 3060 (new)

**Comment by CubeIR** [comment]
Thanks for pointing out these issues.

About the mobs with glowing eyes, it seems like there might be some confusion. Minecraft and Vanilla RTX, as they stand now, don’t support PBR for entities. So, if you’ve seen any glowing mobs, they’re probably from a modified version of Vanilla RTX or Minecraft. I can assure you that none of the official images show any glowing mobs -- it’s just not possible with the current version of Minecraft.

Now, onto the warden and the panorama background issues. These are likely game-related problems, not something caused by Vanilla RTX. Since Vanilla RTX doesn’t modify entities (like the warden), I’d suggest checking out the official Minecraft bug tracker website for more info. If these issues haven’t been reported there yet, it would be great if you could do so.

Hope this helps, and thanks again for your feedback!

**Comment by MistakingManx** [comment]
Alright, thanks you for the direction.

I noticed that Vanilla RTX has _strong_ conflicts with the Java UI pack, which is unfortunate because I hate bedrock UI, but that isn't really your fault.
