### ISSUE TITLE
No release version on Github?

### ISSUE THREAD

**Issue by LierschIT** [CubeIR/Vanilla-RTX#4]
Hi CubeIR,

really nice Resource Pack with RTX. I like it very much. Keep the good work. Just a question:
No release download on Github, only over the other sites?

Was just a little confused about that.

Have a nice day!

**Comment by CubeIR** [comment]
Most of the times It is better to the have latest changes, downloading as zip, changing file extension to .mcpack & importing is recommended if you're visiting Github instead of downloading from other websites, so I am a little unsure why someone would want an older version since there are rarely changes that are subject to change soon or are experimental.
