### ISSUE TITLE
Villager garments are broken

### ISSUE THREAD

**Issue by userandpassword** [Cubeir/Vanilla-RTX#40]
While this feature works with other RTX packs such as Defined PBR it does not work with this one. 

Defined PBR
![Captura de pantalla 2024-11-24 101353](https://github.com/user-attachments/assets/e81cb104-5812-44d5-9e2b-52fae8158b6b)
Vanilla RTX
![Captura de pantalla 2024-11-24 101518](https://github.com/user-attachments/assets/8b8ccbb8-f8fb-4462-b9ed-73438d7fa6ca)

**Comment by Cubeir** [comment]
This isn't an issue with Vanilla RTX but rather a bug in the game itself. Some packs you may come across might include workarounds for this bug, but as the name suggests, these are not true fixes.

That said, Vanilla RTX already does include a workaround for this issue (among many others) under the Enhanced/Experimental subpack, which you can optionally enable. It is kept optional for good reasons: workarounds can break with Minecraft updates, rely on undocumented features, or introduce unintended side effects.
For details on the included fixes, how they were addressed, their side effects, and an image guide for enabling them, please visit [this page](https://mcpedl.com/truly-vanilla-rtx/). (There's a dedicated spoiler tab with additional information in the changelogs.)

**Comment by userandpassword** [comment]
This is just a game not an AEC structural analysis software where data integrity and stabillity are such an important thing. 
I have tried this pack in parallel for many years already and never seen a single crash or glitch in both of my computers. That should be enough to enable it by default.

**Comment by Cubeir** [comment]
In my previous response, I pointed you toward enabling a workaround for this issue and explained why it isn’t enabled by default. However, it seems there’s some misunderstanding about the philosophy behind Vanilla RTX, so I’d like to clarify further.

This isn’t about structural analysis or data integrity but rather about keeping the pack clean, pure, and focused solely on the base necessities. The idea is to maximize compatibility by minimizing the areas it touches—staying as close as possible to how ray tracing would be implemented strictly for vanilla resources.

The Enhanced/Experimental subpack is optional because it introduces workarounds for not just one but several issues, including this one, but it also brings side effects. For example, the villager workaround you're looking for can cause Z-fighting without ray tracing enabled and some shimmering on the entities. Additionally, these changes can conflict with other resource packs, servers, or non-default vanilla scenarios.

By default, Vanilla RTX only includes the bare minimum necessary (primarily PBR-compatible content for the textures/blocks directory) to ensure seamless integration as though it were a natural extension of the vanilla game or easily compatible with other resource packs. The Enhanced option sacrifices this universality to address specific issues but does so at the cost of reduced compatibility (even if rare or for specific cases).
Things like a particle enhancement, model adjustments to work around issues, or similar modifications have always been completely outside the scope of this project, thus they will remain optional.

I hope this clears up the reasoning behind the decision. Even if you personally have not experienced any issues with a particular workaround, it does not dictate the same for everyone else. Vanilla RTX is made to account for all.
