### ISSUE TITLE
warden isn't lit up and soul tourches emit yellow light

### ISSUE THREAD

**Issue by D2Lx0wse** [CubeIR/Vanilla-RTX#6]
![warden](https://user-images.githubusercontent.com/92229936/173339792-5df86077-744e-4b73-8fa8-47c7b03d373a.png)

**Comment by CubeIR** [comment]
Warden is currently bugged with ray tracing (same with ray tracing), the resource pack does not modify mobs/entities (probably the same bug: https://bugs.mojang.com/browse/MCPE-132747)
Soul torches emit the wrong color of light is also another game-related issue rather than resource pack:
https://bugs.mojang.com/browse/MCPE-112916

**Comment by SandboChang** [comment]
> Warden is currently bugged with ray tracing (same issue with horses), the resource pack does not modify mobs/entities (probably the same bug: https://bugs.mojang.com/browse/MCPE-132747) Soul torches emit the wrong color of light is also another game-related issue rather than resource pack: https://bugs.mojang.com/browse/MCPE-112916

thanks for clarifying, was mentioning this on mcpedl, I hope this got fixed soon lol

**Comment by CubeIR** [comment]
MC 1.19.11 should fix this issue
